#!/bin/bash

. /etc/site-setup.conf
BATS_TEST=${BATS_TEST:-""}
BATS_TEST_ROOT=${BATS_TEST_ROOT:-""}
if [ -n "$BATS_TEST" ]; then
	. "$BATS_TEST_ROOT/site-setup.conf.example"
fi

get_password() {
	len=12
	if [ $# = "1" ]; then len="$1"; fi
	</dev/urandom tr -dc 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789_' | head -c$len; echo ""
}

is_verbose() {
	if [ "$VERBOSE" = True ]; then return 0; else return 1; fi
}

is_debug() {
	if [ "$DEBUG" = True ]; then return 0; else return 1; fi
}

